FROM node:17-alpine3.12

WORKDIR /code

COPY ./src/frontend/package.json /code
COPY ./src/frontend/webpack.config.js /code
COPY ./src/frontend/.babelrc /code

RUN npm i -g npm-check-updates
RUN ncu -u

RUN npm install
RUN npm audit fix

RUN mkdir /code/dist
RUN chmod 777 /code/dist


CMD ["npm", "run", "build"]