version: "2"
services:
  myproject:
    image: "${APP}:${WEBSERVICE}-${WEBSERVICE_VERSION}"
    container_name: "${APP}-${WEBSERVICE}"

    ports:
     - "5000:5000"

    volumes:
     - ../../src/backend/webservice/package.json:/code/package.json
     - ../../src/backend/webservice/index.js:/code/index.js
     - ../../src/backend/webservice/routes:/code/routes/
     - ../../src/backend/webservice/controllers:/code/controllers/
     - ../../src/backend/webservice/services:/code/services/
     - ../../src/backend/webservice/models:/code/models/

    networks:
      - "network_${APP}"

networks:
  network_myproject:
    external:
      name: "mongodb_network_${APP}"
