version: "2"
services:
  myproject:
    image: "${APP}:${WEBAPP}-${WEBAPP_VERSION}"
    container_name: "${APP}-${WEBAPP}"

    ports:
     - "3001:3000"

    volumes:
     - ../../src/backend/webapp/package.json:/code/package.json
     - ../../src/backend/webapp/index.js:/code/index.js
     - ../../src/frontend/build:/code/build
