version: "2"
services:
  mongodb:
    image: mongo
      
    ports:
     - "27017:27017"

    container_name: myproject-mongodb

    environment:
    #//TODO Apply env var for user and password
    # Création de l'utilisateur admin de la base de données admin avec les privilèges root
    - MONGO_INITDB_ROOT_USERNAME=admin
    # Création du mot de passe de l'utilisateur admin
    - MONGO_INITDB_ROOT_PASSWORD=docker
    # Créé une base de donnée au nom ${NAME_DB} vide
    - MONGO_INITDB_DATABASE=myproject

    entrypoint: /bin/sh
    # command: -c "chown mongodb:mongodb -R /data && /usr/local/bin/docker-entrypoint.sh mongod"
    command: -c "chmod a+r -R /data && /usr/local/bin/docker-entrypoint.sh mongod"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/configdb:/data/configdb
      - ./data/db:/data/db
      - ./data/json_db:/data/json_db

    networks: 
      network_myproject:
        ipv4_address: 172.27.0.1
  
  
  mongodb_debug:
    image: mongo

    stdin_open: true
    tty: true
    
    entrypoint: /bin/sh
    command: -s 
    #command: -c "chown mongodb:mongodb -R /data"
    ports:
     - "27017:27017"

    volumes:
    #  - ./data:/data/
     - ./data/configdb:/data/configdb
     - ./data/db:/data/db
     - ./data/json_db:/data/json_db

networks: 
  network_myproject:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24
          gateway: 172.27.0.2
