# user configuration
version:=1.0
revision:=1
reference=

shell_executor=bash

up:
	$(shell_executor) ./scripts/docker_commands_script.sh start

down:
	$(shell_executor) ./scripts/docker_commands_script.sh stop

