shell_executor=bash

test:
	$(shell_executor) ./scripts/docker_commands_script.sh test

build_builder_front:
	$(shell_executor) ./scripts/docker_commands_script.sh build_builder_front

build_front_bundle:
	$(shell_executor) ./scripts/docker_commands_script.sh build_front_bundle

build_wa:
	$(shell_executor) ./scripts/docker_commands_script.sh build_wa

build_ws:
	$(shell_executor) ./scripts/docker_commands_script.sh build_ws

up_wa:
	$(shell_executor) ./scripts/docker_commands_script.sh up_wa

up_ws:
	$(shell_executor) ./scripts/docker_commands_script.sh up_ws

up_debug_front_bundle:
	$(shell_executor) ./scripts/docker_commands_script.sh up_debug_front_bundle

down_wa:
	$(shell_executor) ./scripts/docker_commands_script.sh down_wa

down_ws:
	$(shell_executor) ./scripts/docker_commands_script.sh down_ws